# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_auto_20180526_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='transaction',
        ),
        migrations.AddField(
            model_name='prescription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='blockchain.Transaction'),
        ),
    ]
